Update keep_serv00.yml

diff --git a/.github/workflows/keep_serv00.yml b/.github/workflows/keep_serv00.yml
--- a/.github/workflows/keep_serv00.yml
+++ b/.github/workflows/keep_serv00.yml
@@ -90,9 +90,8 @@ jobs:
           
           sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -T ${{ env.SERVER_USERNAME }}@${{ env.SERVER_HOSTNAME }} 2>/dev/null << EOF
             set -e 
-            curl -Ls -H "Cache-Control: no-cache" "https://raw.githubusercontent.com/scattlights/Serv00/main/bash/keep.sh?$(date +%s)" -o keep.sh || { echo 'Script download failed'; exit 1; }
-            cat keep.sh
-            bash keep.sh "${{ env.UDPPORT }}" || { echo 'Script execution failed'; exit 1; }
+            curl -Ls -H "Cache-Control: no-cache" "https://raw.githubusercontent.com/co2f2e/Serv00/main/bash/keep_serv00.sh?$(date +%s)" -o keep_serv00.sh || { echo 'Script download failed'; exit 1; }
+            bash keep_serv00.sh "${{ env.UDPPORT }}" || { echo 'Script execution failed'; exit 1; }
             if [ $? -eq 0 ]; then
               echo
               echo -e "\033[32mSuccess!!!\033[0m"
